### PR TITLE
Broken typescript example

### PR DESCRIPTION
**Pull request by vojty**
Run `./node_modules/.bin/tsc --noEmit`

### CODE REVIEW

**Comment by jamuhl** [comment]
@Vovan-VE would you mind checking this PR - types just where added by your last PR - so a little help would help - as I myself do not use typescript at all (and do not really care for it)

**Comment by vojty** [comment]
I'll look into it, maybe @Vovan-VE could help me

**Comment by vojty** [comment]
remaining errors:
```
10:20 $ ./node_modules/.bin/tsc
index.d.ts:24:24 - error TS2713: Cannot access 'IcuFormats.number' because 'IcuFormats' is a type, but not a namespace. Did you mean to retrieve the type of the property 'number' in 'IcuFormats' with 'IcuFormats["number"]'?

24         [key: string]: IcuFormats.number;
                          ~~~~~~~~~~~~~~~~~

index.d.ts:59:20 - error TS2430: Interface 'IcuInstance' incorrectly extends interface 'ThirdPartyModule'.
  Types of property 'type' are incompatible.
    Type '"i18nFormat"' is not assignable to type '"3rdParty"'.

59   export interface IcuInstance extends ThirdPartyModule {
                      ~~~~~~~~~~~


Found 2 errors.
```

**Comment by Vovan-VE** [comment]
Hello.

The 1st error: I just got `IcuFormats` from here <https://github.com/i18next/i18next-icu/issues/12#issuecomment-578893063>. I don't know any details about this structure. Maybe @dyniper provide some details? Replacing `IcuFormats.number` with `IcuFormats["number"]` produce more errors due to recursion.

The 2nd error is then children interface `IcuInstance.type` defined as `"i18nFormat"` is not assignable to parent interface `ThirdPartyModule.type` which is defined as `"3rdParty"`. Here I just follow literally to:
https://github.com/i18next/i18next-icu/blob/f46d0bfb32df95093673fb6ab0e195381d88c196/src/index.js#L11-L13
If parent interface defined so, then it means you cannot change `type` like this.

**Comment by Vovan-VE** [comment]
I suppose, `Intl.NumberFormatOptions` should be used instead of this crafted object
https://github.com/i18next/i18next-icu/blob/f46d0bfb32df95093673fb6ab0e195381d88c196/index.d.ts#L15-L19

**Comment by Vovan-VE** [comment]
...and `Intl.DateTimeFormatOptions` for two similar objects below there
https://github.com/i18next/i18next-icu/blob/f46d0bfb32df95093673fb6ab0e195381d88c196/index.d.ts#L28-L31
https://github.com/i18next/i18next-icu/blob/f46d0bfb32df95093673fb6ab0e195381d88c196/index.d.ts#L42-L45

**Comment by vojty** [comment]
@Vovan-VE feel free to push changes :)

**Comment by Vovan-VE** [comment]
I also tried to comment out `type`
https://github.com/i18next/i18next-icu/blob/f46d0bfb32df95093673fb6ab0e195381d88c196/src/index.js#L13
but I cannot run tests even before this.

**Comment by Vovan-VE** [comment]
`npm test` sais that `Promise` is not defined. Probably, some dependencies are outdated.
node 12.13

```
18 02 2020 18:31:43.294:INFO [framework.browserify]: bundle built
18 02 2020 18:31:43.305:INFO [karma]: Karma v1.4.1 server started at http://0.0.0.0:9876/
18 02 2020 18:31:43.305:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
18 02 2020 18:31:43.312:INFO [launcher]: Starting browser PhantomJS
18 02 2020 18:31:43.531:INFO [PhantomJS 2.1.1 (Linux 0.0.0)]: Connected on socket EBotkANsv9VLpnroAAAA with id 43711429

  icu format
    basic parse
      ✓ should parse
      ✓ should parse (AR)
    with formatter
      ✓ should parse with custom format
    with i18next
      ✗ "before all" hook
	Can't find variable: Promise
	defer@/tmp/node_modules/i18next/dist/cjs/i18next.js:183:0 <- /tmp/454badde459db454f68b813137afd542.browserify:436:28
	init@/tmp/node_modules/i18next/dist/cjs/i18next.js:1923:0 <- /tmp/454badde459db454f68b813137afd542.browserify:2176:27
	/tmp/test/icu.spec.js:91:14 <- /tmp/454badde459db454f68b813137afd542.browserify:9046:48


PhantomJS 2.1.1 (Linux 0.0.0): Executed 4 of 4 (1 FAILED) (0.076 secs / 0.014 secs)
TOTAL: 1 FAILED, 3 SUCCESS


1) "before all" hook
     icu format with i18next
     Can't find variable: Promise
defer@/tmp/node_modules/i18next/dist/cjs/i18next.js:183:0 <- /tmp/454badde459db454f68b813137afd542.browserify:436:28
init@/tmp/node_modules/i18next/dist/cjs/i18next.js:1923:0 <- /tmp/454badde459db454f68b813137afd542.browserify:2176:27
/tmp/test/icu.spec.js:91:14 <- /tmp/454badde459db454f68b813137afd542.browserify:9046:48


npm ERR! Test failed.  See above for more details.
```

**Comment by vojty** [comment]
I did some major changes in devDependencies (upgraded `babel` and replaced `karma` with `jest`), hope it's ok.

**Comment by vojty** [comment]
@jamuhl fyi ready for review

**Comment by jamuhl** [comment]
@Vovan-VE looks ok to me - if ok for you I will merge an pubish

**Comment by Vovan-VE** [comment]
Yes, surely

**Comment by vojty** [comment]
bump

**Comment by jamuhl** [comment]
published in i18next-icu@1.2.1

**Comment by vojty** [comment]
thanks :)

**Pull request merged**
